# Generated by Django 3.0.2 on 2020-01-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbtMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=10)),
                ('mrating', models.CharField(max_length=10)),
                ('mcast', models.CharField(max_length=10)),
                ('mdate', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='MovieReg',
        ),
    ]
