# Generated by Django 3.0.2 on 2020-01-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_auto_20200124_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abtmovie',
            name='mdate',
            field=models.CharField(max_length=20),
        ),
    ]
